"""
Django settings for Shareish mapsite project.

Generated by 'django-admin startproject' using Django 3.2.10.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""
import datetime
from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

SECRET_KEY = os.environ.get('SECRET_KEY')
# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG') == "True"

DEV = os.environ.get('DEV') == "True"
DEV_DOMAIN = "127.0.0.1:8081"
DEV_URL = "http://" + DEV_DOMAIN
DEV_API_URL = "http://127.0.0.1:8000"

PROD_DOMAIN = "shareish.org"
PROD_URL = "https://" + PROD_DOMAIN
PROD_API_URL = PROD_URL

APP_DOMAIN = DEV_DOMAIN if DEV else PROD_DOMAIN
APP_URL = DEV_URL if DEV else PROD_URL
API_URL = DEV_API_URL if DEV else PROD_API_URL

print(APP_URL)
print(API_URL)

ALLOWED_HOSTS = ['web', '127.0.0.1', 'localhost', APP_DOMAIN.split(":")[0]]

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.gis',
    'rest_framework',
    'rest_framework.authtoken',
    'mail_templated',
    'corsheaders',
    'djoser',
    'channels',
    'mymap.apps.MymapConfig',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',
    'allauth.socialaccount.providers.openid_connect',
    'allauth.socialaccount.providers.mediawiki',
    'allauth.socialaccount.providers.facebook',
    'allauth.socialaccount.providers.microsoft',
    'allauth.socialaccount.providers.apple',
    'allauth.socialaccount.providers.github',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'allauth.account.middleware.AccountMiddleware',
]

ROOT_URLCONF = 'mapsite.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        #'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.media',

            ],
        },
    },
]

# /!\ use Redis channel layer in production
WSGI_APPLICATION = 'mapsite.wsgi.application'
ASGI_APPLICATION = 'mapsite.asgi.application'



AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
]

CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels.layers.InMemoryChannelLayer'
    }
}

# CHANNEL_LAYERS = {
#     "default": {
#         "BACKEND": "channels_redis.core.RedisChannelLayer",
#         "CONFIG": {
#             "hosts": [("127.0.0.1", 6379)],
#         },
#     },
# }


# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.contrib.gis.db.backends.postgis',
        'HOST': os.environ.get('POSTGRES_DB'),
        'NAME': os.environ.get('POSTGRES_NAME'),
        'PASSWORD': os.environ.get('POSTGRES_PASSWORD'),
        'PORT': os.environ.get('POSTGRES_PORT'),
        'USER': os.environ.get('POSTGRES_USER'),
    }
}
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = os.environ.get('EMAIL_HOST')
EMAIL_PORT = 587
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD')
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER
EMAIL_USE_TLS = os.environ.get('EMAIL_USE_TLS')


MEDIA_ROOT = BASE_DIR / "mediafiles"
MEDIA_URL = '/media/'

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "handlers": {
        "console": {"class": "logging.StreamHandler"},
    },
    "loggers": {
        "django": {
            "handlers": ["console"],
            "level": "INFO",
        },
        'allauth': {
            'handlers': ['console'],
            'level': 'DEBUG',
        },
    },
}

LOGIN_URL = 'login/'
LOGIN_REDIRECT_URL = 'index/'
LOGOUT_REDIRECT_URL = 'login/'

AUTH_USER_MODEL = 'mymap.User'

# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Europe/Brussels'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = '/static'

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework.authentication.TokenAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
}

CORS_ALLOW_ALL_ORIGINS = DEV

CORS_ALLOWED_ORIGINS = [
    "http://ui",
    "http://localhost:8081",
    "http://localhost:8000",
    "http://localhost",
    APP_URL,
]


ALLOWED_PROXY_HOSTS = [
    "www.repaircafe.org",
    "www.levolontariat.be",
]


DOMAIN = APP_DOMAIN
SITE_NAME = 'Shareish'

DJOSER = {
    'LOGIN_FIELD': 'email',
    'PASSWORD_RESET_CONFIRM_URL': 'reset-password/confirm/{uid}/{token}',
    'EMAIL': {
        'activation': 'mymap.mail.ActivationEmail',
        'confirmation': 'mymap.mail.ConfirmationEmail',
    },
    'SEND_ACTIVATION_EMAIL': True,  # also send if email has changed
    'SEND_CONFIRMATION_EMAIL': True,  # registration or activation
    'PASSWORD_CHANGED_EMAIL_CONFIRMATION': True,
    'ACTIVATION_URL': 'activate/{uid}/{token}',

    'SERIALIZERS': {
        'user': 'mymap.serializers.UserSerializer',
        'current_user': 'mymap.serializers.UserSerializer',
        'user_create': 'mymap.serializers.UserRegistrationSerializer',
        'user_update': 'mymap.serializers.UserSerializer',
    },
    
}
 

ACCOUNT_EMAIL_VERIFICATION = "none"
#LOGIN_REDIRECT_URL = DEV_URL
LOGIN_REDIRECT_URL = f"{DEV_URL}/map"

ACCOUNT_LOGOUT_ON_GET = True

SOCIALACCOUNT_LOGIN_ON_GET = True
SOCIALACCOUNT_AUTO_SIGNUP = True

SOCIALACCOUNT_EMAIL_AUTHENTICATION = True
SOCIALACCOUNT_EMAIL_AUTHENTICATION_AUTO_CONNECT = True

ACCOUNT_AUTHENTICATION_METHOD = 'email'

ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_UNIQUE_EMAIL = True 

SOCIALACCOUNT_ADAPTER = 'mymap.adapter.SocialAccountAdapter'


CORS_ALLOW_CREDENTIALS = True

SESSION_COOKIE_DOMAIN = None
SESSION_COOKIE_SECURE = False
CSRF_COOKIE_SECURE = False

#https://docs.allauth.org/en/latest/socialaccount/providers/index.html
SOCIALACCOUNT_PROVIDERS = {
    'google':{
        'APP':{
            'client_id': os.environ.get('GOOGLE_CLIENT_ID'),
            'secret': os.environ.get('GOOGLE_SECRET'),
        }
    },
    "openid_connect": {
        "APPS": [
            {
              "provider_id": "openstreetmap",
              "name": "OpenStreetMap",
              "client_id": os.environ.get('OPENSTREETMAP_CLIENT_ID'),
              "secret": os.environ.get('OPENSTREETMAP_SECRET'),
              "settings": {
                  "server_url": "https://master.apis.dev.openstreetmap.org",
                  "token_auth_method": "client_secret_post",
              },
            },
        ],
        'SCOPE': [
            'openid',
        ],
    },
    'mediawiki': {
        'REST_API': 'https://meta.wikimedia.org/w/rest.php',
        'USERPAGE_TEMPLATE': 'https://meta.wikimedia.org/wiki/{username}',

        # Identify your application with a descriptive user agent.
        # Format (generic template):
        #   <client>/<version> (<contact info>) [<extra lib>/<version> ...]
        # Contact info can be a user page URL, project URL, or email.
        'USER_AGENT': 'shareish/0.7 (http://shareish.org)',
        'SCOPE': ['mwoauth-authonlyprivate'],
        'APP':{
            'client_id': os.environ.get('MEDIAWIKI_CLIENT_ID'),
            'secret': os.environ.get('MEDIAWIKI_SECRET'),
            'key': '',   
        },
    },
    #ONLY HTTPS
    'facebook': {
        'METHOD': 'oauth2',  # Set to 'js_sdk' to use the Facebook connect SDK
        #'SDK_URL': '//connect.facebook.net/{locale}/sdk.js',
        'SCOPE': ['email', 'public_profile'],
        #'AUTH_PARAMS': {'auth_type': 'reauthenticate'},
        'INIT_PARAMS': {'cookie': True},
        'FIELDS': [
            'id',
            'first_name',
            'last_name',
            'middle_name',
            'name',
            'name_format',
            'picture',
            'short_name'
        ],
        #'EXCHANGE_TOKEN': True,
        #'LOCALE_FUNC': 'path.to.callable',
        #'VERIFIED_EMAIL': False,
        'VERSION': 'v13.0',
        'GRAPH_API_URL': 'https://graph.facebook.com/v13.0',
        'APP':{
            'client_id': os.environ.get('FACEBOOK_CLIENT_ID'),
            'secret': os.environ.get('FACEBOOK_SECRET'),
            'key': '',
        }
    },
    #OK but does not work in dev prod
    "microsoft": {
        "APPS": [
            {
                "client_id": os.environ.get('MICROSOFT_CLIENT_ID'),
                "secret": os.environ.get('MICROSOFT_SECRET'),
                "settings": {
                    "tenant": "organizations",
                    # Optional: override URLs (use base URLs without path)
                    "login_url": "https://login.microsoftonline.com",
                    "graph_url": "https://graph.microsoft.com",
                }
            }
        ],
        'AUTH_PARAMS':{
            'redirect_uri': 'http://localhost:8000/accounts/microsoft/login/callback/'
        },
        'SCOPE':[
            'openid', 'email', 'profile', 'User.Read'
        ],
    },
    #Need to be register as company
    "apple": {
        "APPS": [{
            # Your service identifier.
            "client_id": "your.service.id",

            # The Key ID (visible in the "View Key Details" page).
            "secret": "KEYID",

             # Member ID/App ID Prefix -- you can find it below your name
             # at the top right corner of the page, or it’s your App ID
             # Prefix in your App ID.
            "key": "MEMAPPIDPREFIX",

            "settings": {
                # The certificate you downloaded when generating the key.
                "certificate_key": """-----BEGIN PRIVATE KEY-----
                s3cr3ts3cr3ts3cr3ts3cr3ts3cr3ts3cr3ts3cr3ts3cr3ts3cr3ts3cr3ts3cr
                3ts3cr3ts3cr3ts3cr3ts3cr3ts3cr3ts3cr3ts3cr3ts3cr3ts3cr3ts3cr3ts3
                c3ts3cr3t
                -----END PRIVATE KEY-----"""
            }
        }]
    },
    'github': {
        'SCOPE': [
            'user',
            'read:org',
        ],
        'APPS':[{
            'client_id': os.environ.get('GITHUB_CLIENT_ID'),
            'secret': os.environ.get('GITHUB_SECRET'),
            'key': '',
        }],
    },
}

INTERVAL_ACCOUNT_DELETION = datetime.timedelta(days=30)

# Implements xss and mime sniffing protection
SECURE_BROWSER_XSS_FILTER = True
SECURE_CONTENT_TYPE_NOSNIFF = True

SITE_ID = 1