version: '3.9'
volumes:
  postgis-data:
  media_volume:

services:
  db:
    image: postgis/postgis:14-3.2
    volumes:
      - postgis-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    restart: unless-stopped

  web:
    build: backend
    volumes:
      - ./backend:/code
      - media_volume:/code/mediafiles
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    depends_on:
      - db
    restart: unless-stopped

  ui:
    build:
      context: frontend
      target: dev-stage
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - media_volume:/app/web/mediafiles
    ports:
      - "8081:8080"
    depends_on:
      - web
    restart: unless-stopped

  backup:
    build:
      context: backup
    volumes:
      - postgis-data:/backup/postgis
      - media_volume:/backup/mediafiles
      - ./backup/postgres:/backup/shareish_database
      - ./backup/image:/backup/shareish_mediafiles
    depends_on:
      - db
