# Generated by Django 3.2.10 on 2022-04-04 11:30

import datetime
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=20)),
                ('birth_date', models.DateField(blank=True, default=datetime.date.today)),
                ('sign_in_date', models.DateField(auto_now_add=True)),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('username', models.CharField(max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True, max_length=300)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Barter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=500)),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('barter_type', models.CharField(choices=[('DN', 'Donation'), ('LN', 'Loan'), ('BR', 'Barter')], default='BR', max_length=2)),
                ('category1', models.CharField(choices=[('FD', 'Food'), ('AN', 'Animals'), ('EN', 'Arts and Entertainments'), ('CL', 'Collectors'), ('HL', 'Helping hand'), ('DY', 'DIY'), ('BT', 'Beauty and Well-being'), ('CH', 'Childhood'), ('IT', 'IT and Multimedia'), ('GD', 'Garden'), ('HS', 'House'), ('HD', 'Holidays and Week-end'), ('BK', 'Books, CDs and DVDs'), ('SP', 'Sport and Leisure'), ('TS', 'Transport and vehicle'), ('OT', 'Other')], default='OT', max_length=2)),
                ('category2', models.CharField(blank=True, choices=[('FD', 'Food'), ('AN', 'Animals'), ('EN', 'Arts and Entertainments'), ('CL', 'Collectors'), ('HL', 'Helping hand'), ('DY', 'DIY'), ('BT', 'Beauty and Well-being'), ('CH', 'Childhood'), ('IT', 'IT and Multimedia'), ('GD', 'Garden'), ('HS', 'House'), ('HD', 'Holidays and Week-end'), ('BK', 'Books, CDs and DVDs'), ('SP', 'Sport and Leisure'), ('TS', 'Transport and vehicle'), ('OT', 'Other')], max_length=2)),
                ('category3', models.CharField(blank=True, choices=[('FD', 'Food'), ('AN', 'Animals'), ('EN', 'Arts and Entertainments'), ('CL', 'Collectors'), ('HL', 'Helping hand'), ('DY', 'DIY'), ('BT', 'Beauty and Well-being'), ('CH', 'Childhood'), ('IT', 'IT and Multimedia'), ('GD', 'Garden'), ('HS', 'House'), ('HD', 'Holidays and Week-end'), ('BK', 'Books, CDs and DVDs'), ('SP', 'Sport and Leisure'), ('TS', 'Transport and vehicle'), ('OT', 'Other')], max_length=2)),
                ('image', models.ImageField(blank=True, upload_to='tfe/uploads/')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mymap.user')),
            ],
        ),
    ]
