# Generated by Django 3.2.10 on 2022-04-05 08:44

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mymap', '0002_alter_barter_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barter',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, srid=4326),
        ),
    ]
