# Generated by Django 3.2.10 on 2022-04-26 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mymap', '0003_alter_barter_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='tfe/uploads/'),
        ),
        migrations.AlterField(
            model_name='barter',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='tfe/uploads/'),
        ),
    ]
