# Generated by Django 3.2.10 on 2022-04-26 18:31

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mymap', '0004_auto_20220426_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barter',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326),
        ),
        migrations.CreateModel(
            name='BarterImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='tfe/uploads/')),
                ('barter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mymap.barter')),
            ],
        ),
    ]
