# Generated by Django 3.2.10 on 2022-04-27 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mymap', '0005_auto_20220426_2031'),
    ]

    operations = [
        migrations.AddField(
            model_name='barter',
            name='in_progress',
            field=models.BooleanField(default=True),
        ),
    ]
