# Generated by Django 3.2.10 on 2022-07-13 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mymap', '0007_auto_20220706_1254'),
    ]

    operations = [
        migrations.RenameModel('Barter', 'Item'),
        migrations.RenameModel('BarterImage', 'ItemImage'),
        migrations.RenameField('Item', 'barter_type', 'item_type'),
        migrations.RenameField('ItemImage', 'barter', 'item')
    ]
