# Generated by Django 3.2.10 on 2022-07-13 13:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mymap', '0008_auto_20220713_1550'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itemimage',
            options={'ordering': ['item']},
        ),
        migrations.AlterField(
            model_name='item',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to=settings.AUTH_USER_MODEL),
        ),
    ]
