# Generated by Django 3.2.10 on 2022-08-09 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mymap', '0014_auto_20220808_1147'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='recurrent',
            field=models.BooleanField(default=False),
        ),
    ]
