# Generated by Django 3.2.10 on 2022-08-09 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mymap', '0015_item_recurrent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='recurrent',
            new_name='is_recurrent',
        ),
    ]
