# Generated by Django 3.2.10 on 2022-08-09 14:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mymap', '0016_rename_recurrent_item_is_recurrent'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='enddate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='startdate',
            field=models.DateField(default=datetime.date(2022, 8, 9)),
        ),
    ]
