# Generated by Django 3.2.10 on 2022-08-09 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mymap', '0017_auto_20220809_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='enddate',
            field=models.DateField(null=True),
        ),
    ]
