# Generated by Django 3.2.10 on 2022-08-14 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mymap', '0019_auto_20220813_1756'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='image',
        ),
    ]
