# Generated by Django 3.2.10 on 2022-08-14 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mymap', '0020_remove_item_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='mymap.item'),
        ),
    ]
