# Generated by Django 3.2.10 on 2022-08-14 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mymap', '0021_conversation_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='slug',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
