# Generated by Django 3.2.10 on 2022-08-18 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mymap', '0022_conversation_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='in_progress',
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
