# Generated by Django 3.2.10 on 2022-08-18 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mymap', '0023_alter_item_in_progress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
