# Generated by Django 3.2.10 on 2022-08-21 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mymap', '0025_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemimage',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='userimage',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
