# Generated by Django 3.2.10 on 2022-08-28 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mymap', '0026_auto_20220821_1520'),
    ]

    operations = [
    ]
