# Generated by Django 3.2.10 on 2022-09-06 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mymap', '0028_auto_20220828_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(default='', max_length=20),
        ),
    ]
