# Generated by Django 3.2.10 on 2022-09-21 10:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mymap', '0030_auto_20220921_0948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='enddate',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='startdate',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
