# Generated by Django 3.2.10 on 2022-11-28 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mymap', '0031_auto_20220921_1253'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversation',
            name='up2date_buyer',
        ),
        migrations.RemoveField(
            model_name='conversation',
            name='up2date_owner',
        ),
        migrations.AddField(
            model_name='message',
            name='seen',
            field=models.BooleanField(default=False),
        ),
    ]
