# Generated by Django 3.2.10 on 2022-12-28 12:49

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mymap', '0032_auto_20221128_1440'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ref_location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='user',
            name='use_ref_loc',
            field=models.BooleanField(default=False),
        ),
    ]
