# Generated by Django 3.2.10 on 2023-01-03 17:40

import django.contrib.gis.db.models.fields
import django.contrib.gis.geos.point
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mymap', '0033_auto_20221228_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='ref_location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, default=django.contrib.gis.geos.point.Point(0.0, 0.0), geography=True, null=True, srid=4326),
        ),
    ]
