# Generated by Django 3.2.10 on 2023-01-04 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mymap', '0034_alter_user_ref_location'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['startdate']},
        ),
        migrations.AddField(
            model_name='user',
            name='dwithin_notifications',
            field=models.PositiveSmallIntegerField(default=10, help_text='Enter maximum distance for new item notifications', null=True),
        ),
    ]
