# Generated by Django 3.2.10 on 2023-01-09 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mymap', '0036_auto_20230107_1656'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='hitcount',
            field=models.IntegerField(default=0, verbose_name='Hit Count'),
        ),
    ]
