# Generated by Django 3.2.10 on 2023-01-09 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mymap', '0037_item_hitcount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='hitcount',
        ),
    ]
