# Generated by Django 3.2.10 on 2023-01-15 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mymap', '0041_auto_20230114_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_type',
            field=models.CharField(choices=[('DN', 'Donation'), ('LN', 'Loan'), ('BR', 'Request'), ('EV', 'Event')], default='BR', max_length=2),
        ),
    ]
