# Generated by Django 3.2.10 on 2023-01-16 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mymap', '0043_auto_20230116_1403'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='last_visit',
        ),
    ]
