# Generated by Django 3.2.10 on 2023-01-17 13:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mymap', '0044_remove_user_last_visit'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='creationdate',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
