# Generated by Django 3.2.10 on 2023-02-25 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mymap', '0046_auto_20230225_0022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='dwithin_notifications',
            field=models.PositiveSmallIntegerField(default=10, help_text='Enter maximum distance for new item and event notifications', null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='mail_notif_freq_conversations',
            field=models.CharField(choices=[('I', 'Instantly'), ('D', 'Daily'), ('N', 'Never')], default='D', max_length=1),
        ),
    ]
