# Generated by Django 4.1.7 on 2023-02-26 22:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mymap', '0047_auto_20230225_1425'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='lastmessagedate',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
