# Generated by Django 3.2.10 on 2023-02-28 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mymap', '0049_alter_userimage_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conversation',
            options={'ordering': ['-lastmessagedate']},
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-date']},
        ),
        migrations.AlterField(
            model_name='item',
            name='category2',
            field=models.CharField(blank=True, choices=[('FD', 'Food and Supplies'), ('AN', 'Pets and Animals'), ('EN', 'Arts, Culture, and Entertainments'), ('CL', 'Collectibles and Decoratives'), ('HL', 'Helping hand and Manual Labor'), ('AT', 'Administrative tasks'), ('DY', 'Do-it-Yourself'), ('BT', 'Beauty and Well-being'), ('HE', 'Health'), ('EY', 'Energy and Heating'), ('CH', 'Childhood'), ('CO', 'Clothes and Shoes'), ('IT', 'Multimedia Hardware'), ('CS', 'Informatics Software'), ('GD', 'Gardening and Nature'), ('HS', 'Living spaces and Housing'), ('EQ', 'Tools and Equipments and Ustensils'), ('HD', 'Holidays, Week-end, Leisures'), ('BK', 'Books and Magazines'), ('MD', 'CDs, DVDs, Blu-rays, Discs'), ('SP', 'Sports'), ('TS', 'Transportation, Delivery, Pick-up, Moving'), ('VE', 'Vehicles and Means of transport'), ('OT', 'Other')], default=None, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='category3',
            field=models.CharField(blank=True, choices=[('FD', 'Food and Supplies'), ('AN', 'Pets and Animals'), ('EN', 'Arts, Culture, and Entertainments'), ('CL', 'Collectibles and Decoratives'), ('HL', 'Helping hand and Manual Labor'), ('AT', 'Administrative tasks'), ('DY', 'Do-it-Yourself'), ('BT', 'Beauty and Well-being'), ('HE', 'Health'), ('EY', 'Energy and Heating'), ('CH', 'Childhood'), ('CO', 'Clothes and Shoes'), ('IT', 'Multimedia Hardware'), ('CS', 'Informatics Software'), ('GD', 'Gardening and Nature'), ('HS', 'Living spaces and Housing'), ('EQ', 'Tools and Equipments and Ustensils'), ('HD', 'Holidays, Week-end, Leisures'), ('BK', 'Books and Magazines'), ('MD', 'CDs, DVDs, Blu-rays, Discs'), ('SP', 'Sports'), ('TS', 'Transportation, Delivery, Pick-up, Moving'), ('VE', 'Vehicles and Means of transport'), ('OT', 'Other')], default=None, max_length=2, null=True),
        ),
    ]
