# Generated by Django 3.2.10 on 2023-03-02 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mymap', '0050_auto_20230228_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_type',
            field=models.CharField(choices=[('DN', 'Donation'), ('LN', 'Loan'), ('RQ', 'Request'), ('EV', 'Event')], default='RQ', max_length=2),
        ),
    ]
