# Generated by Django 3.2.10 on 2023-03-07 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mymap', '0053_auto_20230306_1835'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['sign_up_date']},
        ),
        migrations.RenameField(
            model_name='user',
            old_name='sign_in_date',
            new_name='sign_up_date',
        ),
        migrations.AlterField(
            model_name='conversation',
            name='lastmessagedate',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='creationdate',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='description',
            field=models.TextField(blank=True, default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='user',
            name='facebook_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='user',
            name='homepage_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='user',
            name='instagram_url',
            field=models.URLField(blank=True, default=''),
        ),
    ]
