# Generated by Django 3.2.10 on 2023-03-11 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mymap', '0054_auto_20230307_1253'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itemimage',
            options={'ordering': ['item', 'position']},
        ),
        migrations.AddField(
            model_name='itemimage',
            name='position',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='itemimage',
            name='image',
            field=models.ImageField(upload_to='items_images'),
        ),
    ]
