# Generated by Django 3.2.10 on 2023-03-16 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mymap', '0056_auto_20230316_0011'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['sign_up_date']},
        ),
        migrations.AlterField(
            model_name='userimage',
            name='image',
            field=models.ImageField(upload_to='users_images'),
        ),
    ]
