# Generated by Django 3.2.10 on 2023-03-23 16:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mymap', '0058_rename_item_type_item_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['date']},
        ),
        migrations.RemoveField(
            model_name='conversation',
            name='name',
        ),
        migrations.RemoveField(
            model_name='conversation',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='conversation',
            name='slug',
        ),
        migrations.AddField(
            model_name='conversation',
            name='starter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conversations_starter', to=settings.AUTH_USER_MODEL),
        ),
    ]
