# Generated by Django 3.2.10 on 2023-03-26 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mymap', '0061_conversation_remove_buyer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-id']},
        ),
    ]
