# Generated by Django 3.2.10 on 2023-04-03 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mymap', '0062_auto_20230326_1431'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['conversation_id', '-date']},
        ),
    ]
