# Generated by Django 3.2.10 on 2023-04-06 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mymap', '0064_alter_itemcomment_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['conversation_id', '-date']},
        ),
    ]