# Generated by Django 3.2.10 on 2023-04-05 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mymap', '0065_alter_message_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
