# Generated by Django 3.2.10 on 2023-04-05 23:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mymap', '0066_auto_20230406_0050'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('view_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_views', to='mymap.item')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_views', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddConstraint(
            model_name='itemview',
            constraint=models.UniqueConstraint(fields=('item', 'user'), name='unique__mymap_itemviews__item_user'),
        ),
    ]
