# Generated by Django 3.2.10 on 2023-04-05 23:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mymap', '0066_auto_20230406_0107'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='hitcount',
        ),
    ]
