# Generated by Django 3.2.10 on 2023-04-11 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mymap', '0068_remove_item_hitcount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='in_progress',
        ),
    ]
