# Generated by Django 3.2.10 on 2023-04-16 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mymap', '0070_auto_20230414_1517'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='save_item_viewing',
            field=models.BooleanField(default=True),
        ),
    ]
