# Generated by Django 3.2.10 on 2023-04-27 10:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.db.migrations import RunSQL


class Migration(migrations.Migration):

    dependencies = [
        ('mymap', '0073_conversationuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversations', to='mymap.item'),
        ),
        migrations.RunSQL("DELETE FROM mymap_item WHERE user_id IS NULL;", RunSQL.noop),
        migrations.AlterField(
            model_name='item',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='mymap.user'),
        ),
        migrations.AlterField(
            model_name='itemview',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='item_views', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='message',
            name='conversation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='mymap.conversation'),
        ),
        migrations.AlterField(
            model_name='message',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to=settings.AUTH_USER_MODEL),
        ),
    ]
