# Generated by Django 3.2.10 on 2023-04-27 11:07

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mymap', '0074_auto_20230427_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='ref_location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326),
        ),
    ]
