# Generated by Django 3.2.10 on 2023-05-02 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mymap', '0075_alter_user_ref_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemview',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='mymap.item'),
        ),
    ]
