# Generated by Django 3.2.10 on 2023-05-02 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mymap', '0076_alter_itemview_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='is_closed',
            field=models.BooleanField(default=False),
        ),
    ]
