# Generated by Django 3.2.10 on 2023-05-02 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mymap', '0077_conversation_is_closed'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='visibility',
            field=models.CharField(choices=[('PB', 'Public'), ('UL', 'Unlisted'), ('PR', 'Private')], default='PB', max_length=2),
        ),
    ]
