# Generated by Django 3.2.10 on 2023-05-02 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mymap', '0078_item_visibility'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_disabled',
            field=models.BooleanField(default=False),
        ),
    ]
