# Generated by Django 3.2.10 on 2023-05-05 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mymap', '0080_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='action',
            field=models.CharField(choices=[('recover_account', 'Recover Account'), ('delete_account', 'Delete Account')], max_length=50),
        ),
    ]
