# Generated by Django 3.2.10 on 2023-05-05 22:49
# Manually updated by Florent Banneux

from django.db import migrations, models
import django.db.models.deletion
from django.db.migrations import RunSQL


class Migration(migrations.Migration):

    dependencies = [
        ('mymap', '0083_scheduledaccountdeletion'),
    ]

    operations = [
        migrations.RunSQL("DELETE FROM mymap_message WHERE user_id IS NULL;", RunSQL.noop),
        migrations.AlterField(
            model_name='message',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='mymap.user'),
        ),
    ]
