# Generated by Django 3.2.10 on 2023-05-08 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mymap', '0084_alter_message_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='max_users',
            field=models.PositiveIntegerField(default=2),
        ),
    ]
