# Generated by Django 3.2.10 on 2023-05-09 14:18
# Manually updated by Florent Banneux

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mymap', '0085_conversation_max_users'),
    ]

    operations = [
        migrations.RunSQL("UPDATE mymap_item SET visibility = 'DR' WHERE visibility = 'PR';", migrations.RunSQL.noop),
        migrations.AlterField(
            model_name='item',
            name='visibility',
            field=models.CharField(choices=[('PB', 'Public'), ('UL', 'Unlisted'), ('DR', 'Draft')], default='PB', max_length=2),
        ),
    ]
