# Generated by Django 3.2.10 on 2023-05-22 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mymap', '0086_alter_item_visibility'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='closed_reason',
            field=models.CharField(blank=True, choices=[('ON', 'On Shareish'), ('OUT', 'Outside Shareish'), ('NOT', 'Not resolved'), ('OTH', 'Other')], default='', max_length=3),
        ),
    ]
