# Generated by Django 3.2.10 on 2023-09-26 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mymap', '0088_user_mail_notif_freq_osm'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='mail_notif_generalinfo',
            field=models.BooleanField(default=True),
        ),
    ]
