# Generated by Django 4.1.7 on 2023-11-01 22:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mymap', '0089_user_mail_notif_generalinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='closed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closed_conversations', to=settings.AUTH_USER_MODEL),
        ),
    ]
