# Generated by Django 3.2.10 on 2023-11-01 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mymap', '0090_conversation_closed_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversation',
            name='is_closed',
        ),
    ]
