# Generated by Django 3.2.10 on 2023-11-02 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mymap', '0091_remove_conversation_is_closed'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='use_coordinates',
            field=models.BooleanField(default=False),
        ),
    ]
