# Generated by Django 3.2.23 on 2025-02-25 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mymap', '0094_user_mastodon_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermapextracategory',
            name='category',
            field=models.CharField(choices=[('BKC', 'Public bookcases'), ('DEF', 'Defibrillators'), ('DWS', 'Drinking water spots'), ('FDB', 'Food Banks'), ('FDS', 'Food Sharing'), ('FLF', 'Falling fruits'), ('REP', 'Repair Cafes'), ('FRS', 'Free shops'), ('GVB', 'Give boxes'), ('SPK', 'Soup Kitchens')], max_length=3),
        ),
    ]
