# Generated by Django 3.2.23 on 2026-02-19 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mymap', '0098_add_vol_usermapextracategory_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='url',
            field=models.URLField(blank=True, default=''),
        ),
    ]
