# Generated by Django 3.2.23 on 2026-02-19 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mymap', '0099_item_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='url',
        ),
    ]
