# Generated by Django 3.2.23 on 2026-02-27 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mymap', '0099_item_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='preferred_language',
            field=models.CharField(choices=[('FR', 'French'), ('EN', 'English')], default='EN', max_length=2),
        ),
    ]
